apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pd
spec:
  replicas: 1
  template:
    metadata:
      name: personservice
      labels:
        app: personservice
    spec:
      containers:
      - image: rashmit/personservice
        name: personservice
        envFrom:
        - configMapRef:
            name: db-config
